library(shinydashboard)

dash_ui <- dashboardPage(
  dashboardHeader(title = "GROW-DAWGS: WILD-DAWGS",
                          titleWidth = "400px"),

  dashboardSidebar(width = "400px",
    sidebarMenu(id = "tabs",
      menuItem("Stand Variables", 
               tabName = "stand_variables", 
               icon = icon("tree"),
               selectInput("Location", 
                           "Location",
                           c("Piedmont",
                             "Upper Coastal Plain",
                             "Lower Coastal Plain"),
                           selected = 3),
               sliderInput("Hi",
                           "Stand Dominant Height (ft):",
                           min = 1,
                           max = 105,
                           value = 60,
                           step  = .5),
               sliderInput("N0",
                           "Planting Density (trees/acre):",
                           min = 200,
                           max =1200,
                           value = 650,
                           step  = 1),
               helpText("Loblolly Pine Growth and Yield Model for UPC and Piedmont. PMRC Research Paper 1990-2 by B. Borders, W.Harrison, D.Adams, R.Bailey and L.Pienaar.
                                               LCP unpublished model by Cristian R. Montes. Athens, Georgia 2016")),
      menuItem("Management & Costs", 
               icon = icon("fire"), 
               tabName = "actions",
               sliderInput("ThAge",
                           "Thinning Age:",
                           min = 5,
                           max = 35,
                           value = 15),
               sliderInput("ThinDens",
                           "Post-thinning Density (trees/acre):",
                           min = 0,
                           max = 1000,
                           value = 400),
               fluidRow(
                 column(" ",
                        width = 6,
                        numericInput("cstInterest",
                                     "Interest rate (%)",
                                     min   = 0,
                                     max   = 30,
                                     value = 6,
                                     width = "200px"),
                        numericInput("cstSeedling",
                                     "Seedling Costs ($/1k seedlings):",
                                     min   = 0,
                                     max   = 300,
                                     value = 50,
                                     width = "200px"),
                        numericInput("cstPlanting",
                                     "Planting Cost ($/acre):",
                                     min   = 0,
                                     max   = 150,
                                     value = 1,
                                     width = "200px"),
                        numericInput("cstVeg",
                                     "Other establishment costs ($/acre):",
                                     min   = 0,
                                     max   = 300,
                                     value = 50,
                                     width = "200px")),
                 column(" ",
                        width = 6,
                        numericInput("cstAdministration",
                                     "Administration Cost ($/acre):",
                                     min   = 0,
                                     max   = 100,
                                     value = 5,
                                     width = "200px"),
                        
                        numericInput("cstThinning",
                                     "Thinning Costs ($/ton):",
                                     min   = 0,
                                     max   = 300,
                                     value = 150,
                                     width = "200px"),
                        numericInput("cstHarvesting",
                                     "Harvesting Costs ($/ton):",
                                     min   = 0,
                                     max   = 300,
                                     value = 150,
                                     width = "200px"))),
               selectInput("pt_treatment",
                           "Post-thin Treatment",
                           choices = c("None","Fire","Herbicide","Mix"),
                           multiple = F,
                           selected = "None", 
                           width = "200px"),
               conditionalPanel(condition = "input.pt_treatment == 'Fire'",
                                uiOutput("firecostUI")),
               conditionalPanel(condition = "input.pt_treatment == 'Herbicide'",
                                uiOutput("herbcostUI")),
               conditionalPanel(condition = "input.pt_treatment == 'Mix'",
                                uiOutput("mixcostUI")),
               helpText("Only one thinning is allowed in this model.")),
      menuItem("Products", 
               icon = icon("toilet-paper"), 
               tabName = "Products",
               sliderInput("specPr1",
                           "Pulp diameters (tops - min DBH):",
                           min   = 1,
                           max   = 10,
                           value = c(3,4),
                           post  = " in"),
               numericInput("Pr1",
                            "Pulp Price ($/ton):",
                            min   =   0,
                            max   = 200,
                            value = 10,
                            width = "200px"),
               sliderInput("specPr2",
                           "Chip n Saw diameters (tops - min DBH):",
                           min = 1,
                           max = 10,
                           value = c(6,8),
                           post  =" in"),
               numericInput("Pr2",
                            "Chip n Saw price ($/ton):",
                            min = 0,
                            max = 200,
                            value = 20,
                            width = "200px"),
               sliderInput("specPr3",
                           "Sawtimber diameters (tops - min DBH):",
                           min   = 5,
                           max   = 12,
                           value = c(8,10),
                           post  = " in"),
               numericInput("Pr3",
                            "Sawtimber Price ($/ton):",
                            min   = 0,
                            max   = 200,
                            value = 30,
                            width = "200px"),
               helpText("Products are characterized by a minimum top diameter 
                          and a minimum treshold DBH.")),
      menuItem("Results", icon = icon("chart-line"), tabName = "Results",
        menuSubItem("Dominant Height", tabName = "Dominant Height"),
        menuSubItem("Survival", tabName = "survival"),
        menuSubItem("Basal Area", tabName = "Basal Area"),
        menuSubItem("Volume", tabName = "Volume"),
        menuSubItem("Dry Weight", tabName = "Dry Weight"),
        menuSubItem("Diameter", tabName = "Diameter"),
        menuSubItem("Extraction", tabName = "Extraction"),
        menuSubItem("Yield", tabName = "Yield"),
        menuSubItem("Finance", tabName = "Finance"),
        menuSubItem("Diameter Distribution", tabName = "Diameter Distribution"),
        menuSubItem("Bobwhite Quail", tabName = "nobo"),
        menuSubItem("White-tailed Deer", tabName = "deer"),
        menuSubItem("Plant Diversity", tabName = "diversity"))
      )
  ),
  dashboardBody(
    fluidRow(
      tabBox(title = "Results",
             id = "tabset1",
             height = "600px",
             width = 12,
           tabPanel("Dominant Height",
                              plotlyOutput("SIPlot")),
           tabPanel("Survival",
                    plotlyOutput("SurvivalPlot")),
           tabPanel("Basal Area",
                    plotlyOutput("BasalArea")))#,
    #   tabItem(tabName = "actions",
    #           imageOutput("home_img", inline = F)),
    #   tabItem(tabName ="Products",
    #           imageOutput("home_img", inline = F)),
    #   tabItem(tabName ="Dominant Height",
    #           plotlyOutput("SIPlot"),
    #           h2("The dashed line represents a base scenario for a site index 60ft. 
    #               Dominant height calculated as the average height of dominant and co dominant trees.")),
    #   tabItem(tabName ="survival",
    #           plotlyOutput("SurvivalPlot")),
    #   tabItem(tabName ="Basal Area", 
    #           plotlyOutput("BasalArea")),
    #   tabItem(tabName ="Volume",
    #           plotlyOutput("Volume"),
    #           helpText("The dashed line represents a base scenario for the selected site index, 
    #                                   650 tpa at year 0 without any thinnings.")),
    #   tabItem(tabName ="Dry Weight", 
    #           plotlyOutput("DryWeight"),
    #           helpText("The dashed line represents a base scenario for the selected site index, 
    #                                   650 tpa at year 0 without any thinnings.")),
    #   tabItem(tabName ="Diameter", 
    #           plotlyOutput("QMD"),
    #           helpText("The dashed line represents a base scenario for the selected site index, 
    #                                   650 tpa at year 0 without any thinnings.")),
    #   tabItem(tabName ="Extraction", plotOutput("Extraction")),
    #   tabItem(tabName ="Yield", 
    #           downloadButton("downloadData", "Download"),
    #           reactableOutput("Yield.Table")),
    #   tabItem(tabName ="Finance", 
    #           plotlyOutput("Financial"),
    #           reactableOutput("FinanTable")),
    #   tabItem(tabName ="Diameter Distribution",
    #           sliderInput("cstDistributionAge",
    #                       "Distribution Age:",
    #                       min = 1,
    #                       max = 35,
    #                       value = 5),
    #           plotOutput("Distribution")),
    #   tabItem(tabName ="nobo",
    #           plotlyOutput("Quail"),
    #           helpText("Click on treatment options in the legend to hide/isolate lines."),
    #           helpText("Fire: 2-year rotation"),
    #           helpText("Herbicide: Post-thinning application (Arsenal/Escort/Sunset mix)"),
    #           helpText("Mix: Post-thinning Arsenal/Escort/Sunset application 
    #                                   followed by prescribed fire on a 2-year rotation")),
    #   tabItem(tabName ="deer",
    #           plotlyOutput("Deer"),
    #           helpText("Click on treatment options in the legend to hide/isolate lines."),
    #           helpText("Fire: 2-year rotation"),
    #           helpText("Herbicide: Post-thinning application (Arsenal/Escort/Sunset mix)"),
    #           helpText("Mix: Post-thinning Arsenal/Escort/Sunset application 
    #                                   followed by prescribed fire on a 2-year rotation")),
    #   tabItem(tabName ="diversity",
    #           plotlyOutput("Diversity"),
    #           helpText("Click on treatment options in the legend to hide/isolate lines."),
    #           helpText("Fire: 2-year rotation"),
    #           helpText("Herbicide: Post-thinning application (Arsenal/Escort/Sunset mix)"),
    #           helpText("Mix: Post-thinning Arsenal/Escort/Sunset application 
    #                                   followed by prescribed fire on a 2-year rotation"))
    )
  )
)

shinyApp(
  ui = dash_ui,
  server = server,
  options = list(launch.browser = T)
)
